### ISSUE TITLE
Cannot get this to make video appear

### ISSUE THREAD

**Issue by Hyppy** [wgcowan/VideoStream#3]
I enter the necessary data (http streaming, file location, and get the segment tuning window to show the jwplayer window, but NOTHING appears in the public view of the same object.  What step am I missing to activate the window?

**Comment by wgcowan** [comment]
Try setting the Segment Type in the Video Stream Metadata to "Scene".

Will

**Comment by Hyppy** [comment]
Thank you for your quick reply, and for your help.
Where is this setting?  In the item?   Which tab?

I checked under Item Type Metadata, but I don't have that option.
I did find the free-text field under Streaming Video, and entered "Scene", and still nothing.

![screen shot 2015-03-05 at 2 38 50 pm](https://cloud.githubusercontent.com/assets/11320784/6512955/719d55e8-c345-11e4-9bb9-1176e9066867.png)

**Comment by wgcowan** [comment]
In the Streaming Video tab, there is a Segment Start and Segment End field. It is expecting data in those fields as well since it it assuming each item is a segment of a streaming video. If you want to playback the entire video file, you would enter 0:00:00 in the Segment Start and then enter 0:43:18 in the Segment End field if the video were say 43 minutes and 18 seconds long. Or you would enter 0:02:00 and 0:05:00 if you wanted to playback just a 3 minute segment.

Will

**Comment by Hyppy** [comment]
Thank you for being so responsive.  I really want to stream from our library, and this seems so close to filling the need.

However... its not saving the information in the library.  I put the dates in (both through manual entry and through clicking set at different times), click update, save item, then go right back in, values are set to 0:00:00, and player still doesnt show.

Is there a database update script I need to do to complete the module install?

![screen shot 2015-03-08 at 3 19 20 pm](https://cloud.githubusercontent.com/assets/11320784/6547167/b4009036-c5a6-11e4-8b50-ab83cddc23d7.png)
![screen shot 2015-03-08 at 3 19 03 pm](https://cloud.githubusercontent.com/assets/11320784/6547168/b406cd20-c5a6-11e4-9b10-9f6915ccb6f8.png)

**Comment by wgcowan** [comment]
Unfortunately the process to get the segment tuning module working is complicated because the fields used have different names in each installation of Omeka. Here are the steps to follow. Make sure to backup any files that you modify.

Finding the names of the fields:
Open admin
Click Items
Open and edit an item
goto to Streaming Video tab
Open a developer tool 
On Chrome that would be View/Developers Tools
On Firefox, I suggest using Firebug
Find the field for Segment Start using the developer’s tools
The Field will be name something like "Elements-353-0-text"
do the same for Segment End.
Note the names for these two fields. 
N.B. These fields are named differently on each installation because it depends on what other Metadata Elements you have added to your installation so you have to look them up as described above.

Changing the code:
You need to open an SSH shell on the server that has your code and web server.
cd to the directory containing your code, such as ‘cd /var/www/omeka-2.2.2/'
cd to ‘plugins/VideoStream'
copy the file VideoStreamPlugin.php to VideoStreamPlugin.bkp using ‘cp VideoStreamPlugin.php VideoStreamPlugin.bkp’ to make sure you have a backup incase something goes wrong.
edit VideoStreamPlugin.php
In the last 20 - 30 lines in the file, there are several references to #Elements-xx-0-text fields.
The reference to #Elements-41-0-text refers to the Description field and does not need to be changed. 
The code after the  'jQuery("startButton").click(function(){‘ contains references to the Segment Start and Segment End. The references to #Elements need to be changed to the values you discovered using the developers tools in the web browser.
These lines need to be changed (these lines may not contain the exact same numbers for the #Elements fields):
jQuery("#Elements-353-0-text").val(jQuery("#SegmentStart").val());
jQuery("#Elements-354-0-text").val(jQuery("#SegmentEnd").val());
In addition there are two lines later that read:
jQuery("#Elements-353-0-text").val(jQuery("#SegmentStart").val());
jQuery("#Elements-354-0-text").val(jQuery("#SegmentEnd").val());
Replace the #Elements-353-0-text and #Elements-354-0-text with the values you discovered earlier.
Save the file. 

Now you should be able to use Segment Tuning editor. If some thing goes wrong, then just copy the VideoStreamPlugin.bkp to replace VideoStreamPlugin.php using ‘cp VideoStreamPlugin.bkp VideoSteamPlugin.php'

If you have any problems let me know and I should be able to walk you through this using some screen sharing software like Adobe Connect.

Will

William G. Cowan

**Comment by wmcowan** [comment]
Closing issue.
